const statusCodes = {
	SUCCESS: 200,
	CREATED: 201,
	NOT_FOUND: 404,
	BAD_REQUEST: 400,
	NOT_ALLOWED: 403,
	UNAUTHORIZED: 401,
	CONFLICT: 409,
	INTERNAL_ERROR: 500,
};

const statusCodeMessages = {
	SUCCESS: 'SUCCESS',
	CREATED: 'CREATED',
	NOT_FOUND: 'RESOURCE NOT FOUND',
	BAD_REQUEST: 'BAD REQUEST',
	INTERNAL_ERROR: 'INTERNAL SERVER ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	CONFLICT: 'EMAIL ALREADY IN USE',
	INVALID_OBJECT_ID: 'OBJECT ID IS INVALID',
};

module.exports = {
	statusCodes,
	statusCodeMessages,
};
