const eventNames = {
	USER_ONLINE: 'USER_ONLINE',
	JOIN_ALL_ROOMS: 'JOIN_ALL_ROOMS',
	JOIN_NEW_ROOM: 'JOIN_NEW_ROOM',
	USER_OFFLINE: 'USER_OFFLINE',
	LOGOUT: 'LOGOUT',
	TYPING: 'TYPING',
	DONE_TYPING: 'DONE_TYPING',
	MESSAGE_EVENTS: 'MESSAGE_EVENTS',
	MESSAGE_SEEN: 'MESSAGE_SEEN',
	NEW_MESSAGE_DELIVERED_SEEN: 'NEW_MESSAGE_DELIVERED_SEEN',
	MESSAGES_DELIVERED: 'MESSAGES_DELIVERED',
};

module.exports = eventNames;
