const CONSTANTS = {
  LOGOUT: 'LOGOUT',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  AUTHENTICATED: 'AUTHENTICATED',

  FETCH_CHATLIST: 'FETCH_CHATLIST',
  UPDATE_CURRENT_CHAT: 'UPDATE_CURRENT_CHAT',

  START_TYPING_SEARCH_STRING: 'START_TYPING_SEARCH_STRING',
  START_SEARCHING_MATCHING_USERS: 'START_SEARCHING_MATCHING_USERS',
  FETCHED_USERS_WITH_MATCHING_NAME: 'FETCHED_USERS_WITH_MATCHING_NAME',
  CLOSED_SEARCH_MODEL: 'CLOSED_SEARCH_MODEL',
  CLICK_USER_FROM_LIST: 'CLICK_USER_FROM_LIST',

  UPDATE_USER_ONLINE_STATUS: 'UPDATE_USER_ONLINE_STATUS',
  UPDATE_USER_OFFLINE_STATUS: 'UPDATE_USER_OFFLINE_STATUS',

  LOAD_MESSAGES: 'LOAD_MESSAGES',
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_EDIT_DELETE_EVENT: 'NEW_EDIT_DELETE_EVENT',
  UPDATE_UNREAD: 'UPDATE_UNREAD',

  UPDATE_SEEN_TIME: 'UPDATE_SEEN_TIME',
  UPDATE_DELIVERED_SEEN_TIME: 'UPDATE_DELIVERED_SEEN_TIME',
  UPDATE_UNREAD_ON_CLICK: 'UPDATE_UNREAD_ON_CLICK',

  SET_SOCKET: 'SET_SOCKET',
  JOIN_ALL_ROOMS: 'JOIN_ALL_ROOMS',
  USER_ONLINE: 'USER_ONLINE',
  USER_OFFLINE: 'USER_OFFLINE',
  JOIN_NEW_ROOM: 'JOIN_NEW_ROOM',
  TYPING: 'TYPING',
  DONE_TYPING: 'DONE_TYPING',
  MESSAGES_DELIVERED: 'MESSAGES_DELIVERED',
  MESSAGE_SEEN: 'MESSAGE_SEEN',
  MESSAGE_EVENTS: 'MESSAGE_EVENTS',
  NEW_MESSAGE_DELIVERED_SEEN: 'NEW_MESSAGE_DELIVERED_SEEN',
};

export default CONSTANTS;
